import type { Metadata } from "next";
import {Poppins} from "next/font/google";
import "./globals.scss";
import Header from "../components/Header";

const poppins = Poppins({ subsets: ["latin"] , weight: ["600", "900"]});

export const metadata: Metadata = {
  title: "Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
        <body className={poppins.className}>
            <Header/>
            <div className="container">
                {children}
            </div>
        </body>
    </html>
  );
}
